### ISSUE TITLE
espm library roadmap

### ISSUE THREAD

**Issue by nic11** [skyrim-multiplayer/skymp#100]
Do a rework for different aspects of ESPM library for loading esm/esp files.

Planned changes:
- [ ] More comments documenting internals, including links to UESP wiki
- [x] Unit tests for iterating GRUP children (#99)
- [ ] Reworked structure of loaded file. Representing file as a tree consisting of GRUPs and entries
- [ ] Bonus implied from previous item: getting rid of dirty hacks like changing unused record fields to store additional data
- [ ] Better interface for working with file internals
- [x] Support memory mapping
- [ ] Maybe something else...

**Comment by Pospelove** [comment]
After a private talk, closing all "roadmap" issues for now to standardize issue form.
