### ISSUE TITLE
Infrastructure Roadmap

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#64]
**CI/CD**
- [ ] Perform Windows and Linux builds.
- [ ] Test if CMake build is able to produce `dist` directory with the expected content.
- [ ] TypeScript code formatting.
- [x] C++ code formatting.
- [ ] CMake code formatting.

**Build system**
- [x] Measure the time it takes for each `add_subdirectory` in top-level `CMakeLists.txt` to be done to understand which projects are eating up CMake generation times.
- [ ] Remove `skyrimPlatform.d.ts` from `skymp5-functions-lib`. The `skyrimPlatform.ts` built by `TSConverter` should be used.
- [ ] Npm install should not dump warnings into the output stream.
- [ ] Npm install commands should not be called if everything is already installed, because it's slow
- [ ] Custom targets (and these are all targets, except for C++ targets) are being built every time, and not only when the files they depend on have changed. This slows down the build and should be fixed.
- [ ] Remove `dev_service` (JS part of the build system). Reimplement its functionality in CMake.
- [ ] Remove legacy `vs_startup_project`.
- [ ] Add and document ability to develop and use certain subprojects instead of the whole repository.
- [ ] Ensure that `CMAKE_BINARY_DIR` is `${CMAKE_SOURCE_DIR}/build` (#82).
- [ ] Ensure that all `pdb` files are placed into `build/dist`.
- [ ] Visual Studio should adequately display source tree for C++ and non-C++ targets.

**Build system: Dependency management**
It would be nice to unify the process of dependencies installation and fetch all of them from vcpkg:
- [x] CommonLibSSE
- [ ] TiltedCore
- [ ] TiltedHooks
- [ ] TiltedReverse
- [ ] TiltedUI
- [ ] TiltedOnline (only `ui_process` is required currently)
- [x] SKSE64
- [x] xbyak
- [x] directxtk (it seems we already use vcpkg version, just remove outdated files from the repo)
- [ ] frida
- [ ] ctpl
- [x] CEF
- [ ] cr
- [ ] MakeID
- [ ] npm dependencies (super-experimental)

**Platform/compiler support**
- [x] Add Dockerfile for building on Linux.
- [x] #95

**Feature deprecation/removal**
- [ ] Rewrite TypeScript part of the server in C++, drop NodeJS.
- [ ] Remove existing CLI.
- [ ] Remove `server-settings.json` in favor of CLI.
- [ ] Use SLikeNet for browser messages instead of WebSocket.
- [ ] We should remove hacky `_libkey.js`.
- [ ] NPCs and Papyrus scripts should be whitelisted on the server.

**Remove unnecessary downloads**
Downloads should be controlled by external tooling. Client/CEF should not download anything from the server.
- [ ] Bundle UI with the client, not the server.
- [ ] Remove `skymp5-client.js` and its update system from the server.

**Privacy**
- [ ] Should not set `enable-media-stream` in Chromium by default.

WIP. Feel free to leave comments.

**Comment by Pospelove** [comment]
After a private talk, closing all "roadmap" issues for now to standardize issue form.
